export const LOGIN_START='LOGIN_START'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_ERROR='LOGIN_ERROR'

export const REGISTER_START='REGISTER_START'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_ERR='REGISTER_ERR'

export const GET_QUESTION_START='GET_QUESTION_START'
export const GET_QUESTION_SUCCESS='GET_QUESTION_SUCCESS'
export const GET_QUESTION_ERR='GET_QUESTION_ERR'

export const GET_QUES_AD_START='GET_QUES_AD_START'
export const GET_QUES_AD_SUCCESS='GET_QUES_AD_SUCCESS'

export const GET_QUES_AD_ERR='GET_QUES_AD_ERR'
